version: "3.8"

services:
  postgres:
    image: postgres:17
    container_name: viatab-postgres-local
    environment:
      POSTGRES_DB: viatab
      POSTGRES_USER: viatab_user
      POSTGRES_PASSWORD: viatab_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - viatab-network

  backend:
    build:
      context: ./viatab-backend
      dockerfile: Dockerfile
    container_name: viatab-backend-local
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/viatab
      SPRING_DATASOURCE_USERNAME: viatab_user
      SPRING_DATASOURCE_PASSWORD: viatab_pass
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - viatab-network

  frontend:
    build:
      context: ./viatab-frontend
      dockerfile: Dockerfile
    container_name: viatab-frontend-local
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8080/api
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - viatab-network

volumes:
  postgres_data:

networks:
  viatab-network:
    driver: bridge
