apiVersion: apps/v1
kind: Deployment
metadata:
  name: viatab-frontend
  namespace: viatab
spec:
  replicas: 2
  selector:
    matchLabels:
      app: viatab-frontend
  template:
    metadata:
      labels:
        app: viatab-frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/frederikhandberg0709/viatab-frontend:latest
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_API_URL
              value: "http://backend-service:8080/api"
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
