name: Frontend CI/CD

on:
  push:
    branches: [main, develop]
    paths: ["viatab-frontend/**", ".github/workflows/frontend-ci.yml"]
  pull_request:
    branches: [main]
    paths: ["viatab-frontend/**"]

permissions:
  contents: read
  packages: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify frontend directory
        run: |
          echo "Current directory: $(pwd)"
          echo "Directory contents:"
          ls -la
          echo "Frontend directory exists: $(test -d viatab-frontend && echo 'yes' || echo 'no')"
          if [ -d viatab-frontend ]; then
            echo "Frontend directory contents:"
            ls -la viatab-frontend/
            echo "package.json exists: $(test -f viatab-frontend/package.json && echo 'yes' || echo 'no')"
            echo "package-lock.json exists: $(test -f viatab-frontend/package-lock.json && echo 'yes' || echo 'no')"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        working-directory: ./viatab-frontend
        run: npm ci

      - name: Run type check
        working-directory: ./viatab-frontend
        run: npm run type-check

      - name: Run linter
        working-directory: ./viatab-frontend
        run: npm run lint

      - name: Run tests
        working-directory: ./viatab-frontend
        run: npm test -- --coverage --watchAll=false

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./viatab-frontend/coverage/lcov.info
          flags: frontend
          name: frontend-coverage
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Build application
        working-directory: ./viatab-frontend
        run: npm run build
        env:
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL || 'http://localhost:8080/api' }}

      - name: Build Docker image
        if: github.ref == 'refs/heads/main'
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/viatab-frontend:${{ github.sha }} ./frontend
          docker tag ghcr.io/${{ github.repository_owner }}/viatab-frontend:${{ github.sha }} ghcr.io/${{ github.repository_owner }}/viatab-frontend:latest

      - name: Login to GitHub Container Registry
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image
        if: github.ref == 'refs/heads/main'
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/viatab-frontend:${{ github.sha }}
          docker push ghcr.io/${{ github.repository_owner }}/viatab-frontend:latest
