name: Security Scan

on:
  schedule:
    - cron: "0 2 * * 1" # Run weekly on Mondays during 02:00 at night
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs"
          scan-ref: "."
          format: "sarif"
          output: "trivy-results.sarif"

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: "trivy-results.sarif"

      - name: Run OWASP Dependency Check (Backend)
        working-directory: ./viatab-backend
        run: ./mvnw org.owasp:dependency-check-maven:check
        continue-on-error: true

      - name: Setup Node.js for audit
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Install frontend dependencies
        working-directory: ./viatab-frontend
        run: npm ci

      - name: Run npm audit (Frontend)
        working-directory: ./viatab-frontend
        run: npm audit --audit-level=high
        continue-on-error: true

      - name: Upload security scan results
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: |
            viatab-backend/target/dependency-check-report.html
            trivy-results.sarif
          retention-days: 30
