name: Security Scan

on:
  schedule:
    - cron: '0 2 * * 1' # Run weekly on Mondays during 02:00 at night
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-results.sarif'
    
    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: 'trivy-results.sarif'
    
    - name: Run OWASP Dependency Check (Backend)
      working-directory: ./backend
      run: ./mvnw org.owasp:dependency-check-maven:check
      continue-on-error: true
    
    - name: Run npm audit (Frontend)
      working-directory: ./frontend
      run: npm audit --audit-level=high
      continue-on-error: true
    
    - name: Upload security scan results
      uses: actions/upload-artifact@v3
      with:
        name: security-reports
        path: |
          backend/target/dependency-check-report.html
          trivy-results.sarif
          
